/**
*@modelLogoArr
*/
var logoArr=[
{ url: 'agilityjs',        name :'Agility.js'                          }, 
{ url: 'ajax',             name :'Ajax'                                }, 
{ url: 'alfred',           name :'Alfred'                              }, 
{ url: 'ameba',            name :'Ameba'                               }, 
{ url: 'android',          name :'Android'                             }, 
{ url: 'angular',          name :'AngularJS'                           }, 
{ url: 'backbone',         name :'Backbone.js'                         }, 
{ url: 'batman',           name :'BATMAN.JS'                           }, 
{ url: 'bower',            name :'Bower'                               }, 
{ url: 'cappuccino',       name :'Cappuccino'                          }, 
{ url: 'casper',           name :'CasperJS'                            }, 
{ url: 'charles',          name :'Charles'                             }, 
{ url: 'chrome',           name :'Google Chrome'                       }, 
{ url: 'coffeescript',     name :'CoffeeScript'                        }, 
{ url: 'compass-avatar',   name :'compass-avatar'                      }, 
{ url: 'createjs',         name :'createjs'                            }, 
{ url: 'css3',             name :'CSS3'                                }, 
{ url: 'dart',             name :'Dart'                                }, 
{ url: 'dash',             name :'Dash'                                }, 
{ url: 'emacs',            name :'Emacs'                               }, 
{ url: 'ember',            name :'Ember.js'                            }, 
{ url: 'emmet',            name :'Emmet'                               }, 
{ url: 'enchant',          name :'enchant.js'                          }, 
{ url: 'finder',           name :'Finder'                              }, 
{ url: 'firefox',          name :'Direfox'                             }, 
{ url: 'git',              name :'Git'                                 }, 
{ url: 'google_developer', name :'Google Developers'                   }, 
{ url: 'growl',            name :'Growl'                               }, 
{ url: 'grunt',            name :'Grunt'                               }, 
{ url: 'gwt',              name :'Google Webkit Toolkit'               }, 
{ url: 'haml',             name :'Haml.'                               }, 
{ url: 'handlebars',       name :'Handlebars'                          }, 
{ url: 'html5',            name :'HTML5'                               }, 
{ url: 'ie9',              name :'Internet Explorer 9'                 }, 
{ url: 'image_alpha',      name :'ImageAlpha'                          }, 
{ url: 'image_optim',      name :'ImageOptim'                          }, 
{ url: 'ios7',             name :'iOS 7'                               }, 
{ url: 'jasmine',          name :'Jasmine'                             }, 
{ url: 'jenkins',          name :'Jenkins'                             }, 
{ url: 'jquery',           name :'jQuery'                              }, 
{ url: 'js',               name :'JavaScript'                          }, 
{ url: 'json',             name :'JSON'                                }, 
{ url: 'knockout',         name :'Knockout.js'                         }, 
{ url: 'less',             name :'LESS'                                }, 
{ url: 'mocha',            name :'Mocha'                               }, 
{ url: 'nodejs',           name :'node.js'                             }, 
{ url: 'octocat',          name :'Octocat'                             }, 
{ url: 'phantom',          name :'PhantomJS'                           }, 
{ url: 'prototype',        name :'Prototype.js'                        }, 
{ url: 'qunit',            name :'QUnit'                               }, 
{ url: 'redmine',          name :'Redmine'                             }, 
{ url: 'require',          name :'RequireJS'                           }, 
{ url: 'safari',           name :'Safari'                              }, 
{ url: 'sammyjs',          name :'Sammy.js'                            }, 
{ url: 'sass',             name :'Sass'                                }, 
{ url: 'sencha',           name :'Sencha'                              }, 
{ url: 'sourcetree',       name :'SourceTree'                          }, 
{ url: 'sprout_core',      name :'SproutCore'                          }, 
{ url: 'stackoverflow',    name :'Stack Overflow'                      }, 
{ url: 'stylus',           name :'Stylus'                              }, 
{ url: 'sublime',          name :'Sublime Text'                        }, 
{ url: 'titanium',         name :'Titanium'                            }, 
{ url: 'tower',            name :'Tower'                               }, 
{ url: 'typescript',       name :'TypeScript'                          }, 
{ url: 'underscore',       name :'Underscore.js'                       }, 
{ url: 'vagrant',          name :'Vagrant'                             }, 
{ url: 'vim',              name :'Vim'                                 }, 
{ url: 'virtualbox',       name :'VirtualBox'                          }, 
{ url: 'webstorm',         name :'WebStorm'                            }, 
{ url: 'windows8',         name :'Windows 8'                           }, 
{ url: 'wink_toolkit',     name :'Wink Toolkit'                        }, 
{ url: 'wordpress',        name :'WordPress'                           }, 
{ url: 'yeoman',           name :'Yeoman'                              }, 
{ url: 'yui3',             name :'Yahoo! User Interface Library Ver.3' }, 
{ url: 'zepto',            name :'Zepto.js'                            }
];

