  { name:   'agilityjs     '   , url: 'agilityjs ' },
  { name:   'ajax          '   , url: 'ajax      ' },
  { name:   'alfred        '   , url: 'alfred    ' },
  { name:   'ameba         '   , url: 'ameba     ' },
  { name:   'android       '   , url: 'android   ' },
  { name:   'angular       '   , url: 'angular   ' },
  { name:   'backbone      '   , url: 'backbone  ' },
  { name:   'batman        '   , url: 'batman    ' },
  { name:   'bower         '   , url: 'bower     ' },
  { name:   'cappuccino    '   , url: 'cappuccino' },
  { name:   'casper        '   , url: 'casper    ' },
  { name:   'charles       '   , url: 'charles   ' },
  { name:   'chrome        '   , url: 'chrome    ' },
  { name:   'coffeescript  '   , url: 'coffeescript' },
  { name:   'compass-avatar'   , url: 'compass-avatar' },
  { name:   'createjs      '   , url: 'createjs  ' },
  { name:   'css3          '   , url: 'css3      ' },
  { name:   'dart          '   , url: 'dart      ' },
  { name:   'dash          '   , url: 'dash      ' },
  { name:   'emacs         '   , url: 'emacs     ' },
  { name:   'ember         '   , url: 'ember     ' },
  { name:   'emmet         '   , url: 'emmet     ' },
  { name:   'enchant       '   , url: 'enchant   ' },
  { name:   'finder        '   , url: 'finder    ' },
  { name:   'firefox       '   , url: 'firefox   ' },
  { name:   'git           '   , url: 'git       ' },
  { name:   'google_developer' , url: 'google_developer' },
  { name:   'growl         '   , url: 'growl     ' },
  { name:   'grunt         '   , url: 'grunt     ' },
  { name:   'gwt           '   , url: 'gwt       ' },
  { name:   'haml          '   , url: 'haml      ' },
  { name:   'handlebars    '   , url: 'handlebars' },
  { name:   'html5         '   , url: 'html5     ' },
  { name:   'ie9           '   , url: 'ie9       ' },
  { name:   'image_alpha   '   , url: 'image_alpha' },
  { name:   'image_optim   '   , url: 'image_optim' },
  { name:   'ios7          '   , url: 'ios7      ' },
  { name:   'jasmine       '   , url: 'jasmine   ' },
  { name:   'jenkins       '   , url: 'jenkins   ' },
  { name:   'jquery        '   , url: 'jquery    ' },
  { name:   'js            '   , url: 'js        ' },
  { name:   'json          '   , url: 'json      ' },
  { name:   'knockout      '   , url: 'knockout  ' },
  { name:   'less          '   , url: 'less      ' },
  { name:   'mocha         '   , url: 'mocha     ' },
  { name:   'nodejs        '   , url: 'nodejs    ' },
  { name:   'octocat       '   , url: 'octocat   ' },
  { name:   'phantom       '   , url: 'phantom   ' },
  { name:   'prototype     '   , url: 'prototype ' },
  { name:   'qunit         '   , url: 'qunit     ' },
  { name:   'redmine       '   , url: 'redmine   ' },
  { name:   'require       '   , url: 'require   ' },
  { name:   'safari        '   , url: 'safari    ' },
  { name:   'sammyjs       '   , url: 'sammyjs   ' },
  { name:   'sass          '   , url: 'sass      ' },
  { name:   'sencha        '   , url: 'sencha    ' },
  { name:   'sourcetree    '   , url: 'sourcetree' },
  { name:   'sprout_core   '   , url: 'sprout_core' },
  { name:   'stackoverflow '   , url: 'stackoverflow' },
  { name:   'stylus        '   , url: 'stylus    ' },
  { name:   'sublime       '   , url: 'sublime   ' },
  { name:   'titanium      '   , url: 'titanium  ' },
  { name:   'tower         '   , url: 'tower     ' },
  { name:   'typescript    '   , url: 'typescript' },
  { name:   'underscore    '   , url: 'underscore' },
  { name:   'vagrant       '   , url: 'vagrant   ' },
  { name:   'vim           '   , url: 'vim       ' },
  { name:   'virtualbox    '   , url: 'virtualbox' },
  { name:   'webstorm      '   , url: 'webstorm  ' },
  { name:   'windows8      '   , url: 'windows8  ' },
  { name:   'wink_toolkit  '   , url: 'wink_toolkit' },
  { name:   'wordpress     '   , url: 'wordpress ' },
  { name:   'yeoman        '   , url: 'yeoman    ' },
  { name:   'yui3          '   , url: 'yui3      ' },
  { name:   'zepto         '   , url: 'zepto     ' },
